# -*- mode: ruby -*-
# vi: set ft=ruby :

$setup = <<-'SETUP'
sudo cp /vagrant/my.cnf /etc/my.cnf
sudo cp /vagrant/s3.cnf /etc/s3.cnf

sudo yum update -y
sudo yum upgrade -y
sudo yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
sudo yum install -y glibc-locale-source glibc-langpack-en vim wget curl which jemalloc
sudo localedef -i en_US -f UTF-8 en_US.UTF-8

sudo echo "SELINUX=disabled" > /etc/selinux/config
sudo echo "SELINUXTYPE=targeted" >> /etc/selinux/config

if [[ ! -f /etc/yum.repos.d/mariadb.repo ]]
then
  curl -LsS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | sudo bash
fi
sudo yum update -y
sudo yum install -y MariaDB-server MariaDB-client maxscale MariaDB-columnstore-engine MariaDB-s3-engine MariaDB-server

sudo yum install -y git cmake golang
go get github.com/rcbensley/brimming

sudo systemctl enable mariadb
sudo systemctl start mariadb

sudo systemctl enable mariadb-columnstore
sudo systemctl start mariadb-columnstore

if [[ -d /etc/my.cnf.d ]]
then
  sudo rm -Rf /etc/my.cnf.d
fi

SETUP

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"

  config.vm.network "forwarded_port", guest: 3306, host: 3306
  # config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "public_network", bridge: "en0: Wi-Fi (Wireless)"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.name = "mariadb105"
    vb.cpus = 8
  end

  config.vm.provision "shell", inline: $setup
end
