CREATE DATABASE IF NOT EXISTS test;
USE test;

GRANT CREATE, ALTER, CREATE VIEW, SELECT, INSERT, UPDATE, DELETE, ALTER ROUTINE, EXECUTE, DROP, INDEX, TRIGGER ON test.* to 'cd_test'@'localhost' identified by 'cd_test000';

DROP TABLE IF EXISTS cd_test;
CREATE TABLE cd_test(i INT NOT NULL PRIMARY KEY AUTO_INCREMENT);

DROP TABLE IF EXISTS cd_test_trigger;
CREATE TABLE cd_test_trigger(i INT NOT NULL PRIMARY KEY AUTO_INCREMENT);

DELIMITER $$
DROP PROCEDURE IF EXISTS sp_cd_test $$
CREATE DEFINER=`cd_test`@`localhost` PROCEDURE sp_cd_test()
LANGUAGE SQL
NOT DETERMINISTIC
MODIFIES SQL DATA
SQL SECURITY DEFINER
BEGIN
INSERT INTO cd_test () VALUES ();
END $$
DELIMITER ;

DROP FUNCTION IF EXISTS f_cd_test;
CREATE DEFINER=`cd_test`@`localhost` FUNCTION f_cd_test () RETURNS INT
	RETURN (SELECT 1);

DROP VIEW IF EXISTS v_cd_test;
CREATE DEFINER=`cd_test`@`localhost` VIEW v_cd_test
	AS SELECT * FROM cd_test;

DROP TRIGGER IF EXISTS cd_test_inc;
CREATE DEFINER=`cd_test`@`localhost` TRIGGER cd_test_inc
	AFTER INSERT ON cd_test FOR EACH ROW 
		INSERT INTO cd_test_trigger () VALUES ();


