#!/usr/bin/env sh

SQL=(
"SELECT TABLE_SCHEMA,TABLE_NAME,DEFINER,SECURITY_TYPE FROM information_schema.VIEWS"
"SELECT TRIGGER_SCHEMA,TRIGGER_NAME,EVENT_OBJECT_SCHEMA, EVENT_OBJECT_TABLE, DEFINER,SQL_MODE FROM information_schema.triggers"
"SELECT EVENT_SCHEMA,EVENT_NAME,DEFINER,STARTS,ENDS,STATUS,LAST_EXECUTED,COMMENT FROM information_schema.events"
"SELECT ROUTINE_SCHEMA,ROUTINE_NAME,ROUTINE_TYPE, ROUTINE_NAME, DATA_TYPE, DEFINER,SECURITY_TYPE,SQL_MODE FROM information_schema.routines"
)

for ((i = 0; i < ${#SQL[@]}; i++))
do
	mysql --show-warnings -A -U -e "${SQL[$i]}"
done
