# -*- mode: ruby -*-
# vi: set ft=ruby :

$setup = <<-'SETUP'
sudo mkdir -p /mnt/db/data
sudo mkdir -p /mnt/db/logs

sudo cp /vagrant/my.cnf /mnt/db/my.cnf
sudo cp /vagrant/init.sql /mnt/db/init.sql

sudo yum update -y
sudo yum upgrade -y
sudo yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
sudo yum install -y glibc-locale-source glibc-langpack-en vim wget curl which jemalloc
sudo localedef -i en_US -f UTF-8 en_US.UTF-8

sudo echo "SELINUX=disabled" > /etc/selinux/config
sudo echo "SELINUXTYPE=targeted" >> /etc/selinux/config

if [[ ! -f /etc/yum.repos.d/mariadb.repo ]]
then
  curl -LsS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | sudo bash
  sudo yum update -y
fi
sudo yum install -y MariaDB-server MariaDB-client MariaDB-backup MariaDB-connect-engine

sudo chown -R vagrant:vagrant /mnt/db
sudo chmod 775 /mnt/db/my.cnf

#sudo systemctl enable mariadb
#sudo systemctl start mariadb

#sudo yum install -y maxscale MariaDB-columnstore-engine MariaDB-s3-engine
#sudo systemctl enable mariadb-columnstore
#sudo systemctl start mariadb-columnstore
#sudo yum install -y git cmake golang
#go get github.com/rcbensley/brimming

mysql < /vagrant/setup.sql

if [[ -d /etc/my.cnf.d ]]
then
  sudo rm -Rf /etc/my.cnf.d
fi

sudo echo "!include /mnt/db/my.cnf" > /etc/my.cnf
SETUP

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"

  #config.vm.network "forwarded_port", guest: 3306, host: 3306
  # config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "public_network"# , bridge: "en0: Wi-Fi (Wireless)"

  config.vm.provider "libvirt" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: $setup
end
